import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import type { Placement } from './boundary';
import type { GapModel } from './gap-stitch';

import { computeGapStitches } from './gap-stitch';

/**
 * Real-asset gap stitch (plan 017) over a **Vegas road ramp meeting a junction slab** — the crack diagnosed
 * in-game. The two boundaries meet at a handful of points (variant A) then diverge, so the pass produces real
 * vertex moves on stock geometry. The DFFs are regenerated by `npm run test:fixtures` into gitignored
 * `tests/original/`; the placements are their stock IPL instances (US 1.0).
 */
const ROAD = {
  name: 'vegassroad0522a',
  path: 'tests/original/world/vegassroad0522a.dff',
  placement: { position: [1567.390625, 843.2265625, 10.078125], rotation: [0, 0, 0, 1] } as Placement,
};
const SLAB = {
  name: 'vgssspagjun08',
  path: 'tests/original/world/vgssspagjun08.dff',
  placement: { position: [1496.90625, 843.1484375, 6.5859375], rotation: [0, 0, 0, 1] } as Placement,
};
const haveFixtures = existsSync(ROAD.path) && existsSync(SLAB.path);

/** Read a fixture DFF into a GapModel (positions + triangles + placement). */
function gapModel(fixture: typeof ROAD): GapModel {
  const clump = parseDff(new Uint8Array(readFileSync(fixture.path)).buffer);
  const geometries = clump.geometries.map((geometry) => ({
    positions: geometry.positions,
    triangles: geometry.triangles.map((triangle) => ({ a: triangle.a, b: triangle.b, c: triangle.c })),
  }));

  return { geometries, name: fixture.name, placement: fixture.placement };
}

describe.skipIf(!haveFixtures)('computeGapStitches (real Vegas ramp ↔ slab pair)', () => {
  describe('negative cases', () => {
    it('stitches nothing when the two are moved 500 units apart', () => {
      const shifted: GapModel = {
        ...gapModel(SLAB),
        placement: {
          position: [SLAB.placement.position[0], SLAB.placement.position[1], SLAB.placement.position[2] + 500],
          rotation: SLAB.placement.rotation,
        },
      };
      const { stats } = computeGapStitches([gapModel(ROAD), shifted]);
      expect(stats.stitched + stats.tjunctions + stats.skirted).toBe(0);
    });
  });

  describe('positive cases', () => {
    it('welds the boundary points where the ramp meets the slab (variant A) on stock geometry', () => {
      const { moves, stats } = computeGapStitches([gapModel(ROAD), gapModel(SLAB)]);

      expect(stats.stitched).toBeGreaterThan(0);
      expect((moves.get(ROAD.name)?.length ?? 0) + (moves.get(SLAB.name)?.length ?? 0)).toBeGreaterThan(0);
      // Every move stays local (a hairline nudge, not a wild jump): within ~1 unit of the original position.
      for (const list of moves.values()) {
        for (const move of list) {
          expect(
            Math.hypot(move.newPos[0] - move.pos[0], move.newPos[1] - move.pos[1], move.newPos[2] - move.pos[2]),
          ).toBeLessThan(1);
        }
      }
    });
  });
});
