import type { ImgArchive } from '@opensa/renderware/archive/img-archive';
import type { ProcObjPlacement } from '@opensa/renderware/map/procobj-scatter';

import { buildColliders } from '@opensa/renderware/collision/build-colliders';
import { buildCollisionIndex } from '@opensa/renderware/collision/collision-index';
import { groupRulesBySurface, scatterProcObjects } from '@opensa/renderware/map/procobj-scatter';
import { parseProcObj } from '@opensa/renderware/parsers/text/procobj.parser';
import { parseSurfaceNames } from '@opensa/renderware/parsers/text/surfinfo.parser';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { stripProcObj } from '../strip/procobj';
import { buildMapDefinitions } from './world';

export interface ProcObjConvertOptions {
  archive: ImgArchive;
  gamePath: string;
  /** Only convert species whose impostor bbox is at least this tall (excludes grass/small bushes). */
  heightThreshold: number;
  outPath: string;
  /** Safety cap on total placed objects (HD count); the set is thinned to the lowest-lottery survivors. */
  procObjMax: number;
  /** sourceName → registration. Only `--dff` models that have an impostor are candidates. */
  species: ReadonlyMap<string, ProcObjSpecies>;
}

/** Per converted species: the stock HD model id + its registered impostor (id/alias) + bbox height (the gate). */
export interface ProcObjSpecies {
  hdId: number;
  height: number;
  impostorAlias: string;
  impostorId: number;
}

const IPL_REL = 'data/maps/lodtrees_procobj.ipl';
const IPL_DAT = 'DATA\\MAPS\\lodtrees_procobj.IPL';

/**
 * Convert every `--dff ∩ procobj` species from runtime scatter into static IPL instances: reuse the engine's
 * vanilla `scatterProcObjects`, thin it (MINDIST min-spacing + a global cap — static can't materialise the full
 * runtime density), emit each as an HD instance + its impostor LOD (text-internal `lod`), and strip those species
 * from `procobj.dat`. Returns the gta.dat IPL line to register (or null when nothing qualifies).
 */
export function convertProcObj(options: ProcObjConvertOptions): null | { datLine: string; objects: number } {
  const { archive, gamePath, heightThreshold, outPath, procObjMax, species } = options;
  const procObjText = readFileSync(join(gamePath, 'data', 'procobj.dat'), 'utf8');

  // Convert every `--dff ∩ procobj` species (only those with an impostor). `--procobj-height` (default 0) is an
  // optional gate to drop short clutter; the user otherwise curates the set through `--dff`.
  const eligible = new Set([...species].filter(([, s]) => s.height >= heightThreshold).map(([model]) => model));
  const rules = parseProcObj(procObjText).filter((rule) => eligible.has(rule.model));
  if (rules.length === 0) {
    return null;
  }
  const converted = new Set(rules.map((rule) => rule.model));
  const minDistByModel = new Map<string, number>();
  for (const rule of rules) {
    minDistByModel.set(rule.model, Math.max(minDistByModel.get(rule.model) ?? 0, rule.minDistance));
  }

  // Scatter (vanilla) over the whole map, then thin per species by MINDIST, then a global lowest-lottery cap.
  const defs = buildMapDefinitions(gamePath, archive);
  const colliders = buildColliders(buildCollisionIndex(archive), defs, { center: [0, 0, 0], radius: Infinity });
  const surfaceNames = parseSurfaceNames(readFileSync(join(gamePath, 'data', 'surfinfo.dat'), 'utf8'));
  const batches = scatterProcObjects(colliders, groupRulesBySurface(rules), surfaceNames, 0, 0);

  const placed: { model: string; placement: ProcObjPlacement }[] = [];
  for (const batch of batches) {
    const vanilla = batch.placements.filter((placement) => placement.lottery < 1);
    for (const placement of cullByMinDistance(vanilla, minDistByModel.get(batch.model) ?? 0)) {
      placed.push({ model: batch.model, placement });
    }
  }
  placed.sort((a, b) => a.placement.lottery - b.placement.lottery);
  const final = placed.slice(0, procObjMax);

  // Emit lodtrees_procobj.ipl: per object an HD instance (lod → its impostor) + the impostor LOD instance.
  const rows: string[] = [];
  final.forEach(({ model, placement }, i) => {
    const s = species.get(model)!;
    const t = [...placement.position, ...iplQuaternion(placement.rotation)].join(', ');
    rows.push(`${s.hdId}, ${model}, 0, ${t}, ${2 * i + 1}`); // HD → the impostor row that follows
    rows.push(`${s.impostorId}, ${s.impostorAlias}, 0, ${t}, -1`); // impostor LOD (leaf)
  });
  writeText(
    join(outPath, IPL_REL),
    ['# Generated by lod-trees-generator — procobj → static', 'inst', ...rows, 'end', ''].join('\r\n'),
  );

  // Strip the converted species from procobj.dat (they no longer scatter at runtime).
  writeText(
    join(outPath, 'data', 'procobj.dat'),
    stripProcObj(procObjText, (m) => !converted.has(m.toLowerCase())).text,
  );

  return { datLine: `IPL ${IPL_DAT}`, objects: final.length };
}

/** Greedy min-distance (XY) cull, spatial-hashed; input is already lottery-sorted so the lowest survive. */
export function cullByMinDistance(placements: readonly ProcObjPlacement[], minDist: number): ProcObjPlacement[] {
  if (minDist <= 0) {
    return [...placements];
  }
  const grid = new Map<string, ProcObjPlacement[]>();
  const minSq = minDist * minDist;
  const kept: ProcObjPlacement[] = [];
  for (const placement of placements) {
    const gx = Math.floor(placement.position[0] / minDist);
    const gy = Math.floor(placement.position[1] / minDist);
    if (!tooClose(grid, gx, gy, placement, minSq)) {
      kept.push(placement);
      const key = `${gx},${gy}`;
      (grid.get(key) ?? grid.set(key, []).get(key)!).push(placement);
    }
  }

  return kept;
}

/** GTA IPL rotation quaternion for a yaw around Z (conjugated, the IPL convention; align is unused by trees). */
export function iplQuaternion(yaw: number): [number, number, number, number] {
  return [0, 0, -Math.sin(yaw / 2), Math.cos(yaw / 2)];
}

function tooClose(
  grid: ReadonlyMap<string, ProcObjPlacement[]>,
  gx: number,
  gy: number,
  p: ProcObjPlacement,
  minSq: number,
): boolean {
  for (let dx = -1; dx <= 1; dx += 1) {
    for (let dy = -1; dy <= 1; dy += 1) {
      for (const q of grid.get(`${gx + dx},${gy + dy}`) ?? []) {
        const ddx = p.position[0] - q.position[0];
        const ddy = p.position[1] - q.position[1];
        if (ddx * ddx + ddy * ddy < minSq) {
          return true;
        }
      }
    }
  }

  return false;
}

function writeText(path: string, text: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}
