/**
 * Asset registration for the impostor LOD models: allocate a free object id per impostor, emit a `lodtrees.ide`
 * (`objs` section), and splice an `IDE` line into `gta.dat` (IDEs load before IPLs).
 */

/** Search window for free object ids: above the low special-model ranges, below the stock model ceiling, so the
 *  new models load on **stock** SA (ids above the max stock id of 18630 silently fail to load without an adjuster). */
const ID_MIN = 4000;
const ID_MAX = 19999;
/** Object flags for the LOD billboards — the value the Proper-Fixes LOD-vegetation mod uses for its tree LODs.
 *  (0x200084: alpha + draw-last + LOD-friendly.) The draw distance is `--draw`. */
const FLAGS = 2097284;
const TXD = 'lodtrees';

/** IMG entry names are ≤ 23 bytes incl `.dff`; the model name is the entry base, so it must be ≤ 19 chars. */
const MAX_MODEL = 19;

/**
 * Assign each impostor model a free object id from the lowest contiguous gap in the stock id space that fits them
 * all (deterministic, sorted). Staying inside the stock range means the models load without a limit adjuster.
 */
export function allocateImpostorIds(models: readonly string[], used: ReadonlySet<number>): Map<string, number> {
  const sorted = [...new Set(models.map((m) => m.toLowerCase()))].sort();
  const start = findFreeBlock(used, sorted.length);
  const ids = new Map<string, number>();
  sorted.forEach((model, i) => ids.set(model, start + i));

  return ids;
}

/** The `lodtrees.ide` text — one `objs` row per impostor model, at the given LOD draw distance. */
export function buildLodTreesIde(ids: ReadonlyMap<string, number>, drawDistance: number): string {
  const rows = [...ids]
    .sort((a, b) => a[1] - b[1])
    .map(([model, id]) => `${id}, ${model}, ${TXD}, ${drawDistance}, ${FLAGS}`);

  return ['# Generated by lod-trees-generator — impostor LOD models', 'objs', ...rows, 'end', ''].join('\r\n');
}

/**
 * The model name SA registers for an impostor (IDE `objs` + the `<model>.dff` IMG entry). Usually the impostor's
 * own `lod<source>` name; when that would overflow the IMG entry limit, a short synthetic alias keyed by index
 * (the DFF still references its `lod<source>` texture inside `lodtrees.txd`, so visuals are unaffected).
 */
export function impostorAlias(name: string, index: number): string {
  const lower = name.toLowerCase();

  return lower.length <= MAX_MODEL ? lower : `lodt${index}`;
}

/** Splice `IDE <path>` into gta.dat right after the last IDE line (so it loads before the IPLs). */
export function patchGtaDat(dat: string, idePath: string): string {
  const eol = dat.includes('\r\n') ? '\r\n' : '\n';
  const lines = dat.split(/\r?\n/);
  let lastIde = -1;
  lines.forEach((line, i) => {
    if (/^\s*IDE\b/i.test(line)) {
      lastIde = i;
    }
  });
  const insert = `IDE ${idePath}`;
  if (lastIde < 0) {
    lines.unshift(insert);
  } else {
    lines.splice(lastIde + 1, 0, insert);
  }

  return lines.join(eol);
}

/** The lowest id starting a run of `count` consecutive unused ids within `[ID_MIN, ID_MAX]`. */
function findFreeBlock(used: ReadonlySet<number>, count: number): number {
  let runStart = -1;
  for (let id = ID_MIN; id <= ID_MAX; id += 1) {
    if (used.has(id)) {
      runStart = -1;
      continue;
    }
    if (runStart < 0) {
      runStart = id;
    }
    if (id - runStart + 1 >= count) {
      return runStart;
    }
  }

  throw new Error(`no free block of ${count} object ids in [${ID_MIN}, ${ID_MAX}]`);
}
